name: Prebuild Sysroot

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  build-debian:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        distro:
          - { distro: debian/unstable, mirror: "" }
          - { distro: debian/sid, mirror: "" }
          - { distro: debian/bookworm, mirror: "" }
          - { distro: debian/bullseye, mirror: "http://archive.debian.org/debian" }
          - { distro: debian/buster, mirror: "http://archive.debian.org/debian" }
          - { distro: debian/stretch, mirror: "http://archive.debian.org/debian" }
          - { distro: debian/jessie, mirror: "http://archive.debian.org/debian" }
          - { distro: ubuntu/noble, mirror: "" }
          - { distro: ubuntu/jammy, mirror: "" }
          - { distro: ubuntu/focal, mirror: "" }
          - { distro: ubuntu/bionic, mirror: "" }
          - { distro: ubuntu/xenial, mirror: "" }
          - { distro: ubuntu/trusty, mirror: "" }
    uses: ./.github/workflows/build-sysroot.yml
    with:
      target_arch: ${{ matrix.arch }}
      distro: ${{ matrix.distro.distro }}
      mirror_url: ${{ matrix.distro.mirror }}
      additional_packages: "build-essential"
      artifact_prefix: sysroot-

  build-alpine:
    strategy:
      matrix:
        arch:
          - aarch64
          - x86_64
        distro:
          - { distro: alpine/latest-stable, mirror: "" }
    uses: ./.github/workflows/build-sysroot.yml
    with:
      target_arch: ${{ matrix.arch }}
      distro: ${{ matrix.distro.distro }}
      mirror_url: ${{ matrix.distro.mirror }}
      additional_packages: build-base
      artifact_prefix: sysroot-

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build-debian
      - build-alpine
    steps:
      - name: Set release tag
        run: echo "RELEASE_TAG=$(date +"%Y%m%d")-git${GITHUB_SHA:0-7}" >> $GITHUB_ENV

      - name: Download sysroot artifact
        uses: actions/download-artifact@v4
        with:
          path: sysroot
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.RELEASE_TAG}}
          files: sysroot/*
